# Title shown in Application Information tab.
title: Cloud Engineering Main
# Sub Title shown in Application Information tab.
description: Create all of the compartments, basic dynamic groups, and policies needed to have a cloud-engineering structure inside the tenancy.
informationalText: Groups and Dynamic Groups will be located inside of the non-default Identity Domain.
schemaVersion: 1.1.0
version: "20190304"

locale: "en"
variableGroups:
  - title: "Identity Domain Configuration"
    variables:
      - domain_id
  - title: "Root Compartment Configuration"
    variables:
      - cloud_engineering_root_compartment_ocid
  - title: "Hidden Variables" 
    visible: false
    variables:
      - tenancy_ocid
      - user_ocid
      - fingerprint
      - private_key_path
      - region
      - private_key_password

variables:
  domain_id:
    title: Identity Domain OCID
    type: string
    description: Do not update this unless you know it is different from the default.

  cloud_engineering_root_compartment_ocid:
    title: Engineer Compartment Root
    description: Select the compartment where the engineer compartments should be created.
    type: oci:identity:compartment:id
