# Title shown in Application Information tab.
title: Cloud Engineering Main
# Sub Title shown in Application Information tab.
description: Create all of the compartments, basic dynamic groups, and policies needed to have a cloud-engineering structure inside the tenancy.
informationalText: Groups and Dynamic Groups will be located inside of the non-default Identity Domain.
schemaVersion: 1.1.0
version: "20190304"

locale: "en"
variableGroups:
  - title: "Identity Domain Configuration"
    variables:
      - home_region
      - domain_id
      - engineer_group_name
  - title: "Compartment Configuration"
    variables:
      - engineer_compartment_base_name
  - title: "DRG Configuration"
    variables:
      - use_drg
      - rpc_peer_region
      - rpc_peer_ocid
  - title: "Hidden Variables" 
    visible: false
    variables:
      - tenancy_ocid
      - user_ocid
      - fingerprint
      - private_key_path
      - region
      - private_key_password

variables:
  # string field
  engineer_compartment_base_name:
    type: string
    minLength: 1
    maxLength: 30
    # pattern: "^[a-z][a-zA-Z0-9]+$"
    # title is used as the label if present
    title: Compartment Name
    # description used as the tooltip if present
    description: Name of the main compartment for all cloud engineers to have a compartment inside of.  The base name here will also get a "-shared" compartment.
    default: cloud-engineering
    required: true

  domain_id:
    title: Identity Domain OCID
    type: string
    description: Already created Identity Domain.

  engineer_group_name:
    title: Name of IAM group for engineers
    type: string
    description: Change as necessary
    default: cloud-engineering-users

  use_drg:
    type: boolean
    title: "Create DRG?"
    description: "Create a DRG at root of tenancy for use with RPC or FastConnect?"
    required: true
    default: false

  rpc_peer_region:
    title: Peer Region for DRG
    type: string
    description: Only define if it is actually peered
    required: false
    visible: use_drg

  rpc_peer_ocid:
    title: Peer OCID for DRG
    type: string
    description: Only define if it is actually peered
    required: false
    visible: use_drg

  home_region:
    title: Home region for tenancy
    description: Select the home region for the tenancy
    type: oci:identity:region:name
    required: true